### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by SebastianSolisFenger** [SebastianSolisFenger/Capstone-API-App#23]
Here's the link to our project: https://github.com/SebastianSolisFenger/Capstone-API-App/projects/2

We are to people working on this project:

## @alexpuente0

**Comment by medaminedev66** [comment]
Hi @SebastianSolisFenger and @alexpuente0, 

Congratulations! 🎉 
Your project is complete! Good luck with your capstone project. 👍




Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by SebastianSolisFenger** [comment]
> Hi @SebastianSolisFenger and @alexpuente0,
> 
> Congratulations! 🎉 Your project is complete! Good luck with your capstone project. 👍
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thanks!
